import 'dart:convert';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:url_launcher/url_launcher.dart';

void main()=>runApp(const JobBridge());
class JobBridge extends StatelessWidget{const JobBridge({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData(colorSchemeSeed:Colors.indigo,useMaterial3:true),home:const Home());}
class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{
int page=0;PlatformFile? resume;String resumeName='No resume selected';final api=TextEditingController(),custom=TextEditingController();final found=<String>[];final chosen=<String>{};final connected=<String>{};
final profile={'Full Name':'','Email':'','Phone':'','Experience':'','Current Company':'','Current Location':'','Expected Salary':'','Notice Period':''};
final portals={'LinkedIn':'https://www.linkedin.com/login','Naukri':'https://login.naukri.com','Indeed':'https://secure.indeed.com/auth','Foundit':'https://www.foundit.in','Company Careers':'https://www.google.com/search?q=company+careers','Greenhouse':'https://www.greenhouse.io/job-board','Lever':'https://jobs.lever.co','Ashby':'https://jobs.ashbyhq.com'};
void note(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
Future<void> pick()async{final r=await FilePicker.platform.pickFiles(type:FileType.custom,allowedExtensions:['pdf','docx'],withData:true);if(r!=null&&r.files.single.bytes!=null)setState(()=>{resume=r.files.single,resumeName=resume!.name});}
Future<void> extract()async{if(resume==null){note('Select resume first');return;}if(api.text.trim().isEmpty){note('Add backend URL for live extraction');return;}try{final u=Uri.parse(api.text.trim().replaceAll(RegExp(r'/$'),'')+'/resume/extract');final q=http.MultipartRequest('POST',u)..files.add(http.MultipartFile.fromBytes('file',resume!.bytes!,filename:resume!.name));final s=await q.send().timeout(const Duration(seconds:30));final b=await s.stream.bytesToString();if(s.statusCode==200){final d=jsonDecode(b);setState(()=>found..clear()..addAll((d['keywords']as List).map((e)=>e.toString())));note('Keywords extracted');}else{note('Extraction failed');}}catch(e){note('Backend not reachable');}}
void addCustom(){final v=custom.text.trim();if(v.isNotEmpty)setState(()=>{if(!found.contains(v))found.add(v);chosen.add(v);custom.clear();});}
Future<void> open(String u)async{await launchUrl(Uri.parse(u),mode:LaunchMode.externalApplication);}
void connect(String p){showDialog(context:context,builder:(c)=>AlertDialog(title:Text('Connect '+p),content:const Text('Login opens on the official portal. Complete login manually, then return and tap MARK CONNECTED. Passwords are not stored.'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),OutlinedButton(onPressed:()=>open(portals[p]!),child:const Text('OPEN LOGIN')),FilledButton(onPressed:(){setState(()=>connected.add(p));Navigator.pop(c);note(p+' connected');},child:const Text('MARK CONNECTED'))]));}
Widget nav(int n)=>Row(children:[if(page>0)OutlinedButton(onPressed:()=>setState(()=>page--),child:const Text('BACK')),const Spacer(),FilledButton(onPressed:()=>setState(()=>page=n),child:Text(n==4?'APPLY TO PORTALS →':'NEXT →'))]);
Widget resumeStep()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('STEP 1 — UPLOAD RESUME',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:12),Card(child:ListTile(leading:const Icon(Icons.description,size:38),title:Text(resumeName),subtitle:const Text('PDF or DOCX'),trailing:FilledButton(onPressed:pick,child:const Text('SELECT')))),TextField(controller:api,decoration:const InputDecoration(labelText:'Live extraction backend URL',hintText:'Free backend URL',border:OutlineInputBorder())),const SizedBox(height:8),FilledButton.icon(onPressed:extract,icon:const Icon(Icons.auto_awesome),label:const Text('EXTRACT FROM RESUME')),const SizedBox(height:12),nav(1)]);
Widget keywordStep()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('STEP 2 — SELECT KEYWORDS',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const Text('Resume se extracted keywords select karo. Fixed nahi hain.'),...found.map((k)=>CheckboxListTile(contentPadding:EdgeInsets.zero,value:chosen.contains(k),title:Text(k),onChanged:(v)=>setState(()=>v==true?chosen.add(k):chosen.remove(k)))),const Divider(),const Text('SELECTED KEYWORDS',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(border:Border.all(color:Colors.grey),borderRadius:BorderRadius.circular(10)),child:Wrap(spacing:6,runSpacing:6,children:chosen.map((k)=>InputChip(label:Text(k),onDeleted:()=>setState(()=>chosen.remove(k)))).toList())),Row(children:[Expanded(child:TextField(controller:custom,onSubmitted:(_)=>addCustom(),decoration:const InputDecoration(labelText:'Add custom keyword'))),IconButton(onPressed:addCustom,icon:const Icon(Icons.add_circle,size:30))]),nav(2)]);
Widget profileStep()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('EXTRACTED PROFILE REVIEW',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const Text('Resume me jo missing hoga usko fill karo. Future applications me reuse hoga.'),...profile.entries.map((e)=>Padding(padding:const EdgeInsets.only(top:10),child:TextFormField(initialValue:e.value,onChanged:(v)=>profile[e.key]=v,decoration:InputDecoration(labelText:e.key,border:const OutlineInputBorder())))),nav(3)]);
Widget portalStep()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('STEP 3 — CONNECT JOB PORTALS',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const Text('Har selected portal ke official login se connect karo.'),...portals.keys.map((p)=>Card(child:ListTile(leading:Checkbox(value:connected.contains(p),onChanged:(v)=>setState(()=>v==true?connected.add(p):connected.remove(p))),title:Text(p),subtitle:Text(connected.contains(p)?'🟢 Connected':'Not connected'),trailing:FilledButton(onPressed:()=>connect(p),child:Text(connected.contains(p)?'MANAGE':'CONNECT'))))),nav(4)]);
Widget applyStep()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('STEP 4 — APPLY TO PORTALS',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),Card(child:ListTile(title:const Text('Resume'),subtitle:Text(resumeName))),Card(child:ListTile(title:const Text('Selected Keywords'),subtitle:Text(chosen.isEmpty?'None':chosen.join(', ')))),const Text('CONNECTED PORTALS',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),...connected.map((p)=>ListTile(leading:const Icon(Icons.check_circle),title:Text(p),trailing:TextButton(onPressed:()=>open(portals[p]!),child:const Text('OPEN')))),const SizedBox(height:20),FilledButton.icon(onPressed:startApply,icon:const Icon(Icons.rocket_launch),label:const Text('START SEARCH & APPLY')),const SizedBox(height:12),const Text('Search → Match → Fill from Resume/Profile → Missing data alert → CAPTCHA/OTP manual → Review/Submit.',textAlign:TextAlign.center),nav(4)]);
void startApply(){if(connected.isEmpty){note('Connect at least one portal');return;}if(chosen.isEmpty){note('Select at least one keyword');return;}showDialog(context:context,builder:(c)=>AlertDialog(title:const Text('JOB SEARCH READY'),content:Text('JOBBRIDGE will use '+chosen.length.toString()+' keywords on '+connected.length.toString()+' connected portals. CAPTCHA/OTP and unsupported fields will pause and show an action-required alert.'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:(){Navigator.pop(c);note('Search engine backend is the next live module to connect.');},child:const Text('START'))]));}
@override Widget build(BuildContext c){final s=[resumeStep(),keywordStep(),profileStep(),portalStep(),applyStep()];return Scaffold(appBar:AppBar(title:Text('JOBBRIDGE AI • '+(page+1).toString()+'/5')),body:SafeArea(child:s[page]));}
}