import 'dart:convert';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:url_launcher/url_launcher.dart';

void main()=>runApp(const JobBridge());
class JobBridge extends StatelessWidget{const JobBridge({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData(colorSchemeSeed:Colors.indigo,useMaterial3:true),home:const Home());}
class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{
int page=0;PlatformFile? resume;String resumeName='No resume selected';final api=TextEditingController();final key=TextEditingController();final List<String> keys=[];final selected=<String>{};
final portals={'LinkedIn':'https://www.linkedin.com/login','Naukri':'https://login.naukri.com','Indeed':'https://secure.indeed.com/auth','Foundit':'https://www.foundit.in','Company Careers':'https://www.google.com/search?q=company+careers','Greenhouse':'https://www.greenhouse.io/job-board','Lever':'https://jobs.lever.co','Ashby':'https://jobs.ashbyhq.com'};
void note(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
Future<void> pick()async{final r=await FilePicker.platform.pickFiles(type:FileType.custom,allowedExtensions:['pdf'],withData:true);if(r!=null&&r.files.single.bytes!=null)setState(()=>{resume=r.files.single,resumeName=resume!.name});}
Future<void> extract()async{if(resume==null){note('Select resume PDF first');return;}if(api.text.trim().isEmpty){note('Add backend URL for live extraction');return;}try{final u=Uri.parse(api.text.trim().replaceAll(RegExp(r'/$'),'')+'/resume/extract');final q=http.MultipartRequest('POST',u)..files.add(http.MultipartFile.fromBytes('file',resume!.bytes!,filename:resume!.name));final s=await q.send();final b=await s.stream.bytesToString();if(s.statusCode==200){final d=jsonDecode(b);setState(()=>keys..clear()..addAll((d['keywords']as List).map((e)=>e.toString())));note(keys.length.toString()+' keywords extracted');}else{note('Extraction failed');}}catch(e){note('Backend not reachable');}}
void add(){final v=key.text.trim();if(v.isNotEmpty&&!keys.contains(v)){setState(()=>keys.add(v));key.clear();}}
Future<void> open(String u)async{await launchUrl(Uri.parse(u),mode:LaunchMode.externalApplication);}
Widget start()=>Padding(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Spacer(),const Icon(Icons.work,size:90),const SizedBox(height:24),const Text('JOBBRIDGE AI',textAlign:TextAlign.center,style:TextStyle(fontSize:30,fontWeight:FontWeight.bold)),const Text('Resume → Keywords → Portals → Jobs',textAlign:TextAlign.center),const Spacer(),FilledButton(onPressed:()=>setState(()=>page=1),child:const Text('START'))]));
Widget resumePage()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('UPLOAD RESUME',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),Card(child:ListTile(leading:const Icon(Icons.picture_as_pdf),title:Text(resumeName),trailing:FilledButton(onPressed:pick,child:const Text('SELECT PDF')))),TextField(controller:api,decoration:const InputDecoration(labelText:'Live extraction backend URL',border:OutlineInputBorder())),const SizedBox(height:8),FilledButton.icon(onPressed:extract,icon:const Icon(Icons.auto_awesome),label:const Text('EXTRACT KEYWORDS')),const SizedBox(height:16),const Text('SELECTED KEYWORDS',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),Wrap(spacing:6,children:keys.map((k)=>InputChip(label:Text(k),onDeleted:()=>setState(()=>keys.remove(k)))).toList()),Row(children:[Expanded(child:TextField(controller:key,onSubmitted:(_)=>add(),decoration:const InputDecoration(labelText:'Add keyword'))),IconButton(onPressed:add,icon:const Icon(Icons.add_circle))]),Row(children:[TextButton(onPressed:()=>setState(()=>page=0),child:const Text('BACK')),const Spacer(),FilledButton(onPressed:()=>setState(()=>page=2),child:const Text('CONTINUE'))])]);
Widget portalPage()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('SELECT JOB PORTALS',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const Text('Choose exactly where JOBBRIDGE should work.'),...portals.entries.map((e)=>Card(child:CheckboxListTile(value:selected.contains(e.key),onChanged:(v)=>setState(()=>v==true?selected.add(e.key):selected.remove(e.key)),title:Text(e.key),secondary:IconButton(icon:const Icon(Icons.open_in_new),onPressed:()=>open(e.value)))),Row(children:[TextButton(onPressed:()=>setState(()=>page=1),child:const Text('BACK')),const Spacer(),FilledButton(onPressed:()=>setState(()=>page=3),child:const Text('CONTINUE'))])]);
Widget done()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('READY',style:TextStyle(fontSize:26,fontWeight:FontWeight.bold)),ListTile(title:const Text('Resume'),subtitle:Text(resumeName)),ListTile(title:const Text('Keywords'),subtitle:Text(keys.isEmpty?'None selected':keys.join(', '))),...selected.map((p)=>ListTile(title:Text(p),trailing:TextButton(onPressed:()=>open(portals[p]!),child:const Text('OPEN PORTAL')))),FilledButton.icon(onPressed:()=>note('Search uses your selected resume keywords and portals.'),icon:const Icon(Icons.search),label:const Text('START JOB SEARCH')),TextButton(onPressed:()=>setState(()=>page=2),child:const Text('BACK'))]);
@override Widget build(BuildContext c){final s=[start(),resumePage(),portalPage(),done()];return Scaffold(appBar:AppBar(title:const Text('JOBBRIDGE AI')),body:SafeArea(child:s[page]));}
}