import 'package:flutter/material.dart';
void main()=>runApp(const JobBridge());
class JobBridge extends StatelessWidget{const JobBridge({super.key});@override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData(colorSchemeSeed:Colors.indigo,useMaterial3:true),home:const Home());}
class Portal{String name;bool selected;String account;bool connected;Portal(this.name,{this.selected=false,this.account='',this.connected=false});}
class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{
final tickets=<Map<String,dynamic>>[
{'name':'Facilities & Administration','location':'Delhi NCR','keywords':'Facilities Manager, Facility Management, Administration Manager, Admin Manager, Vendor Management, AMC Management, SLA Management, Maintenance, Housekeeping, Security, Electrical Maintenance, Interior Projects','score':70,'active':true},
{'name':'Procurement & Commercial','location':'Delhi NCR','keywords':'Procurement Manager, Purchase Manager, Commercial Manager, Vendor Manager, Contracts Manager, RFQ, Vendor Negotiation, Purchase Order, Quotation, SAP, ERP, Contract Management','score':70,'active':true}];
final portals=[Portal('LinkedIn'),Portal('Naukri'),Portal('Indeed'),Portal('Foundit'),Portal('Company Career Pages',selected:true),Portal('Greenhouse',selected:true),Portal('Lever',selected:true),Portal('Ashby',selected:true)];
void connectPortal(Portal p){final a=TextEditingController(text:p.account);final pass=TextEditingController();showDialog(context:context,builder:(c)=>AlertDialog(title:Text('Connect '+p.name),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:a,decoration:const InputDecoration(labelText:'Email / Username / Mobile')),TextField(controller:pass,obscureText:true,decoration:const InputDecoration(labelText:'Password')),const Text('Credentials must not be stored in plain text. OTP, CAPTCHA and MFA remain manual.',style:TextStyle(fontSize:12))]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:(){setState((){p.account=a.text.trim();p.connected=p.account.isNotEmpty;});Navigator.pop(c);},child:const Text('Save & Connect'))]));}
Widget portalCard(Portal p)=>Card(child:CheckboxListTile(value:p.selected,onChanged:(v)=>setState(()=>p.selected=v??false),title:Text(p.name),subtitle:Text(p.connected?'Connected: '+p.account:'Login not connected'),secondary:IconButton(icon:Icon(p.connected?Icons.verified_user:Icons.login),onPressed:()=>connectPortal(p))));
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('JOBBRIDGE AI 🎫')),body:ListView(padding:const EdgeInsets.all(16),children:[const Text('Job Search Tickets',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),...tickets.map((x)=>Card(child:ExpansionTile(title:Text(x['name']),subtitle:Text(x['location']+' • '+x['score'].toString()+'% minimum match'),leading:Switch(value:x['active'],onChanged:(v)=>setState(()=>x['active']=v)),children:[Padding(padding:const EdgeInsets.all(16),child:Wrap(spacing:6,runSpacing:4,children:x['keywords'].split(',').map<Widget>((e)=>Chip(label:Text(e.trim()))).toList()))]))),const SizedBox(height:20),const Divider(),const Text('Select Job Portals',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const Text('Select portals and connect the account you want to use.'),...portals.map(portalCard),const SizedBox(height:12),FilledButton.icon(onPressed:(){},icon:const Icon(Icons.play_arrow),label:const Text('START JOB SEARCH'))]));}